export const authActionTypes = {
  LOGIN_SUBMIT: 'LOGIN_SUBMIT',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT_SUBMIT: 'LOGOUT_SUBMIT',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILED: 'LOGOUT_FAILED',
};
